int _putchar(char);
void reset_to_98(int*);
void swap_int(int*, int*);
void _puts(char*);
void print_rev(char*);
void rev_string(char *s);
void puts2(char *str);
void puts_half(char *str);
void print_array(int *a, int n);
char *_strcpy(char *dest, char *src);
int _atoi(char *s);
int _strlen(char *s);
